module.exports = {
  PER6: [
    {
      id: "per6-q1",
      prompt: "¿Cuál es la idea principal del texto?",
      options: [
        "El precio sigue siendo el único criterio relevante en las decisiones urbanas",
        "En la vida urbana, el tiempo se volvió un recurso central que organiza decisiones económicas, sociales y personales",
        "Las ciudades latinoamericanas resolvieron sus problemas de movilidad y por eso el tiempo vale más",
        "El ocio perdió por completo su importancia frente al trabajo",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto muestra que el tiempo deja de ser un fondo neutro y pasa a influir en consumo, movilidad, descanso, vínculos y prioridades.",
      tip: "Buscá la idea que conecta todos los párrafos, no solo un ejemplo particular.",
      topics: ["mainIdea", "conclusion"],
    },
    {
      id: "per6-q2",
      prompt: "¿Qué decisión aparece en el texto como ejemplo del nuevo valor del tiempo?",
      options: [
        "Elegir comercios cercanos para reducir traslados",
        "Evitar siempre los trámites digitales",
        "Aumentar de manera fija el presupuesto de ocio",
        "Mudarse obligatoriamente al centro de la ciudad",
        "Trabajar menos horas por semana",
      ],
      correctOptionIndex: 0,
      explanation:
        "El segundo párrafo menciona de forma explícita la elección de comercios cercanos, trámites digitales y soluciones que ahorran tiempo.",
      tip: "Cuando el texto enumera ejemplos concretos, la respuesta correcta suele reproducir uno de ellos sin exagerarlo.",
      topics: ["details"],
    },
    {
      id: "per6-q3",
      prompt: "¿Qué ejemplos del texto muestran decisiones orientadas a ahorrar tiempo?",
      options: [
        "Elegir comercios cercanos",
        "Preferir filas más largas",
        "Usar trámites digitales",
        "Mantener costumbres aunque hagan perder tiempo",
        "A y C",
      ],
      correctOptionIndex: 4,
      explanation:
        "El texto menciona expresamente los comercios cercanos y los trámites digitales como decisiones guiadas por el ahorro temporal.",
      tip: "Si una opción combina respuestas, verificá que ambas aparezcan de verdad en el texto.",
      topics: ["details"],
    },
    {
      id: "per6-q4",
      prompt: "¿Qué se infiere del hecho de que algunas personas acepten pagar más por ciertos servicios?",
      options: [
        "Que el precio dejó de importar por completo",
        "Que ganar tiempo puede considerarse un beneficio valioso en agendas muy cargadas",
        "Que los productos más caros siempre son mejores",
        "Que el trabajo explica por sí solo todas las decisiones cotidianas",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto señala que pagar más por soluciones que simplifican la rutina puede resultar razonable cuando el tiempo es escaso.",
      tip: "Inferir no es inventar: buscá el sentido que se desprende del texto sin ir más allá de lo que permite.",
      topics: ["inference", "causeEffect"],
    },
    {
      id: "per6-q5",
      prompt: "¿Qué actividades pueden empezar a percibirse como lujos cuando gran parte del día se consume en desplazamientos y tareas acumuladas?",
      options: [
        "Conversar sin apuro",
        "Cocinar",
        "Aumentar el rendimiento económico",
        "Esperar con paciencia",
        "A, B y D",
      ],
      correctOptionIndex: 4,
      explanation:
        "El texto nombra esas actividades como ejemplos de experiencias valiosas que quedan desplazadas cuando el tiempo cotidiano se vuelve escaso.",
      tip: "Prestá atención a las enumeraciones del quinto párrafo: allí aparecen ejemplos muy literales.",
      topics: ["details", "inference"],
    },
    {
      id: "per6-q6",
      prompt: "¿Qué función cumple el cuarto párrafo dentro del desarrollo del texto?",
      options: [
        "Introduce la idea de que el valor del tiempo también expresa desigualdades",
        "Demuestra que el tiempo importa solo en el consumo de lujo",
        "Niega que exista relación entre ingresos y experiencias urbanas",
        "Cierra el texto con una conclusión definitiva sobre el trabajo",
      ],
      correctOptionIndex: 0,
      explanation:
        "Ese párrafo agrega un matiz clave: no todas las personas pueden pagar por ahorrar tiempo, por lo que la experiencia temporal también se vuelve desigual.",
      tip: "Pensá qué aporta cada párrafo nuevo al argumento general, no solo qué datos menciona.",
      topics: ["structure"],
    },
    {
      id: "per6-q7",
      prompt: "¿Cuál de estas afirmaciones NO se puede sostener a partir del texto?",
      options: [
        "Todas las personas urbanas valoran el tiempo exactamente del mismo modo",
        "El tiempo influye en decisiones de consumo y también en experiencias de bienestar",
        "Algunas personas pueden pagar por soluciones que ahorran tiempo",
        "La agenda cotidiana empieza a influir en elecciones antes guiadas por costumbre",
        "El tiempo gana visibilidad como criterio social",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto afirma lo contrario: la valorización del tiempo no se distribuye de manera homogénea y depende de condiciones sociales distintas.",
      tip: "En preguntas con negación, descartá primero las opciones que el texto sí afirma o sugiere claramente.",
      topics: ["inference"],
      isTricky: true,
    },
    {
      id: "per6-q8",
      prompt: "En el cierre, ¿qué significa que el tiempo ya no actúa como 'fondo silencioso' de la vida urbana?",
      options: [
        "Que el tiempo dejó de existir como marco de la rutina",
        "Que pasó de ser un trasfondo poco pensado a convertirse en un criterio explícito de decisión",
        "Que solo importa cuando se habla de dinero",
        "Que ya no tiene relación con emociones ni vínculos",
        "Ninguna de las anteriores",
      ],
      correctOptionIndex: 1,
      explanation:
        "La expresión indica que el tiempo ya no queda en segundo plano: ahora se considera de forma visible al tomar decisiones.",
      tip: "Cuando el texto usa una metáfora, buscá la opción que traduzca su sentido, no la que la repita literalmente.",
      topics: ["vocabulary", "conclusion"],
    },
    {
      id: "per6-q9",
      prompt: "¿Por qué el texto dice que el tiempo también se vuelve una dimensión de desigualdad?",
      options: [
        "Porque todas las personas tienen el mismo acceso a soluciones rápidas",
        "Porque quienes cuentan con menos recursos suelen depender de servicios más lentos y trayectos más largos",
        "Porque la desigualdad urbana se explica solo por el uso del ocio",
        "Porque el tiempo importa únicamente dentro del hogar",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto relaciona ingresos menores con servicios menos flexibles, trayectos más largos y menos capacidad para comprar ahorro de tiempo.",
      tip: "Si la pregunta apunta a una causa, buscá la relación directa que el texto establece entre dos fenómenos.",
      topics: ["causeEffect", "details"],
    },
    {
      id: "per6-q10",
      prompt: "¿Qué decisiones se presentan al final como evaluadas según el tiempo que demandan cada día?",
      options: [
        "Elegir una escuela",
        "Elegir un lugar para vivir",
        "Elegir un medio de transporte",
        "Las tres decisiones anteriores",
        "Elegir amistades y actividades culturales",
      ],
      correctOptionIndex: 3,
      explanation:
        "El último párrafo enumera exactamente esas tres decisiones como ejemplos de elecciones pensadas por su impacto diario sobre la agenda.",
      tip: "Si el texto enumera varios casos y la pregunta los reúne, revisá si una opción los integra sin agregar otros.",
      topics: ["details"],
    },
    {
      id: "per6-q11",
      prompt: "¿Para qué sirven en el texto ejemplos como comida preparada, compras en línea o atención prioritaria?",
      options: [
        "Para mostrar que la comodidad dejó de ser importante",
        "Para ilustrar cómo el ahorro de tiempo puede justificar ciertos consumos",
        "Para probar que el trabajo es la única actividad valiosa",
        "Para afirmar que todas las personas consumen de la misma manera",
      ],
      correctOptionIndex: 1,
      explanation:
        "Esos ejemplos concretan una idea general: algunas personas pagan más cuando eso les permite simplificar rutinas y ahorrar tiempo.",
      tip: "Pensá qué función cumple el ejemplo dentro del argumento, no solo qué objeto nombra.",
      topics: ["tools", "structure"],
    },
    {
      id: "per6-q12",
      prompt: "Según el texto, el valor del tiempo influye en el trabajo, el descanso y los vínculos personales. ¿Cuál opción resume mejor esa idea?",
      options: [
        "Solo en el trabajo",
        "Solo en el descanso y el ocio",
        "Solo en los vínculos personales",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto afirma que el tiempo no se relaciona únicamente con el trabajo: también afecta el ocio, el descanso y los vínculos.",
      tip: "No reduzcas el alcance del argumento a un solo ámbito si el texto lo amplía explícitamente.",
      topics: ["conclusion", "details"],
      isTricky: true,
    },
    {
      id: "per6-q13",
      prompt: "¿Qué conclusión general se desprende del texto?",
      options: [
        "El dinero dejó de importar en las economías urbanas",
        "El tiempo se convirtió en un criterio cada vez más visible para organizar la vida urbana",
        "Las ciudades lograron equilibrar trabajo, ocio y consumo",
        "La desigualdad urbana ya no depende del acceso a servicios",
      ],
      correctOptionIndex: 1,
      explanation:
        "El cierre resume que el tiempo adquirió peso económico, social y emocional, y que ese cambio reordena prioridades urbanas.",
      tip: "La conclusión correcta integra el recorrido del texto completo, no solo una sección aislada.",
      topics: ["conclusion", "mainIdea"],
    },
    {
      id: "per6-q14",
      prompt: "¿Qué se puede inferir sobre quienes cuentan con menos ingresos?",
      options: [
        "Que suelen disponer de más tiempo libre para compensar sus limitaciones económicas",
        "Que siempre priorizan el ocio por encima del trabajo",
        "Que con frecuencia tienen menos posibilidades de comprar soluciones que reduzcan tiempos",
        "Que viven necesariamente más cerca de los servicios",
        "Que el texto los presenta como indiferentes al valor del tiempo",
      ],
      correctOptionIndex: 2,
      explanation:
        "El texto indica que para ciertos sectores pagar por ahorrar tiempo es una posibilidad real, mientras que para otros sigue siendo un lujo lejano.",
      tip: "Inferí a partir de las desigualdades que el texto describe, sin sumar explicaciones externas.",
      topics: ["inference"],
    },
    {
      id: "per6-q15",
      prompt: "¿Cómo redefine el texto consumos que antes podían verse como 'comodidades secundarias'?",
      options: [
        "Como gastos inútiles en cualquier contexto",
        "Como formas razonables de ordenar rutinas cargadas",
        "Como privilegios exclusivos de turistas",
        "Como prácticas opuestas al bienestar personal",
      ],
      correctOptionIndex: 1,
      explanation:
        "El tercer párrafo afirma que ciertos productos o servicios ya no se perciben solo como comodidades, sino como recursos para organizar agendas exigentes.",
      tip: "Prestá atención a expresiones como 'hoy aparece como': suelen señalar un cambio de interpretación.",
      topics: ["vocabulary", "details"],
    },
    {
      id: "per6-q16",
      prompt: "¿Qué opciones del texto aparecen como servicios o consumos que pueden pagarse para simplificar la rutina?",
      options: [
        "Comida preparada",
        "Atención prioritaria",
        "Compras en línea",
        "Reducción legal de la jornada laboral",
        "A, B y C",
      ],
      correctOptionIndex: 4,
      explanation:
        "El texto menciona esos tres ejemplos como servicios o consumos vinculados al ahorro de tiempo; la reducción legal de la jornada no aparece.",
      tip: "Verificá que cada elemento de una combinación esté realmente nombrado en el texto.",
      topics: ["details"],
    },
    {
      id: "per6-q17",
      prompt: "¿Cómo se organiza principalmente el desarrollo del texto?",
      options: [
        "Presenta un fenómeno urbano, ofrece ejemplos cotidianos, introduce una desigualdad y amplía sus efectos",
        "Cuenta la historia de una sola ciudad y luego la compara con zonas rurales",
        "Reúne estadísticas sobre empleo y termina negando el valor del tiempo",
        "Describe únicamente servicios digitales y su impacto económico",
        "Enumera problemas sin proponer ninguna relación entre ellos",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto avanza desde la presentación del problema hacia ejemplos, desigualdades y efectos sobre prioridades, bienestar y decisiones cotidianas.",
      tip: "Para preguntas de estructura, seguí el orden general del texto y observá cómo se va complejizando el argumento.",
      topics: ["structure"],
    },
    {
      id: "per6-q18",
      prompt: "¿Qué matiz introduce el texto al hablar de actividades sin rendimiento económico inmediato?",
      options: [
        "Que son innecesarias en contextos urbanos exigentes",
        "Que pueden ser esenciales para el bienestar aunque no produzcan un beneficio económico directo",
        "Que solo se valoran en sectores de altos ingresos",
        "Que desaparecieron por completo de la vida urbana",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto aclara que actividades como conversar, caminar o cocinar no generan rendimiento inmediato, pero siguen siendo importantes para el bienestar.",
      tip: "No confundas 'no produce rendimiento económico' con 'no tiene valor'. El texto distingue claramente esas ideas.",
      topics: ["inference", "conclusion"],
      isTricky: true,
    },
    {
      id: "per6-q19",
      prompt: "¿Cuál de estas afirmaciones coincide con el texto?",
      options: [
        "Ahorrar tiempo siempre equivale a gastar menos dinero",
        "El tiempo importa solamente en decisiones laborales",
        "Todas las personas pueden comprar soluciones rápidas del mismo modo",
        "El tiempo adquiere un valor económico, social y emocional",
        "Ninguna de las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "La última línea del texto define justamente al tiempo como un criterio económico, social y emocional con efectos visibles.",
      tip: "La opción correcta suele retomar con precisión una formulación importante del cierre.",
      topics: ["details", "conclusion"],
    },
    {
      id: "per6-q20",
      prompt: "En el texto, ¿qué significa que esta lógica no se distribuye de manera 'homogénea'?",
      options: [
        "Que se reparte de manera idéntica entre todos los sectores",
        "Que afecta sobre todo a zonas rurales",
        "Que no se experimenta de forma igual en todos los grupos sociales",
        "Que solo tiene consecuencias emocionales",
      ],
      correctOptionIndex: 2,
      explanation:
        "El término señala que la posibilidad de ahorrar tiempo o de pagar por él varía según la posición social y los recursos disponibles.",
      tip: "Buscá el sentido contextual de la palabra dentro de la comparación entre distintos sectores sociales.",
      topics: ["vocabulary"],
    },
  ],
  PER7: [
    {
      id: "per7-q1",
      prompt: "¿Cuál es la idea principal del texto?",
      options: [
        "Viajar perdió toda relevancia en la vida contemporánea",
        "El turismo de cercanía expresa un cambio de prioridades en la forma de pensar los viajes",
        "Los destinos lejanos desaparecieron del mapa turístico",
        "La única causa de los cambios en el turismo es la falta de infraestructura",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto no niega el valor de viajar, pero muestra que hoy pesan más la viabilidad, la flexibilidad y la integración con la vida cotidiana.",
      tip: "La idea principal debe captar el cambio de criterio, no quedarse con una causa aislada.",
      topics: ["mainIdea", "conclusion"],
    },
    {
      id: "per7-q2",
      prompt: "¿Qué factores del texto ayudan a explicar el crecimiento del turismo de cercanía?",
      options: [
        "Las restricciones económicas",
        "El poco tiempo disponible para viajes extensos",
        "La obligación de buscar siempre prestigio internacional",
        "A y B",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto menciona con claridad tanto el factor económico como las agendas ajustadas como impulsores de esta modalidad.",
      tip: "Si la respuesta combina causas, comprobá que ambas aparezcan desarrolladas en párrafos distintos del texto.",
      topics: ["causeEffect", "details"],
    },
    {
      id: "per7-q3",
      prompt: "Según el texto, ¿qué caracteriza al turismo de cercanía más allá de recorrer menos kilómetros?",
      options: [
        "Una manera diferente de pensar el viaje según posibilidades concretas",
        "La obligación de pasar vacaciones dentro de la misma ciudad",
        "La búsqueda de experiencias siempre extraordinarias",
        "El rechazo automático de cualquier planificación",
      ],
      correctOptionIndex: 0,
      explanation:
        "El segundo párrafo aclara que no se trata solo de distancia, sino de un modo distinto de concebir el viaje.",
      tip: "Prestá atención a las aclaraciones del tipo 'no consiste solo en...': suelen marcar un matiz central.",
      topics: ["details", "structure"],
    },
    {
      id: "per7-q4",
      prompt: "¿Por qué los viajes largos resultan menos accesibles para muchas familias, según el texto?",
      options: [
        "Porque requieren más dinero, más planificación y mayor margen frente a imprevistos",
        "Porque están prohibidos en la mayoría de los países",
        "Porque ya no generan descanso de ningún tipo",
        "Porque siempre exigen trámites imposibles de resolver",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto enumera de manera literal esos tres factores como parte de la dificultad de organizar viajes extensos.",
      tip: "En preguntas causales, fijate si el texto ofrece una enumeración explícita de razones.",
      topics: ["causeEffect", "details"],
    },
    {
      id: "per7-q5",
      prompt: "¿Cómo presenta el texto a las escapadas breves de dos o tres días?",
      options: [
        "Como experiencias inferiores que no permiten ningún descanso",
        "Como alternativas más realistas en contextos de agendas ajustadas",
        "Como viajes pensados solo para turistas de alto poder adquisitivo",
        "Como una moda sin relación con el trabajo y el tiempo disponible",
        "Como reemplazos obligatorios de las vacaciones anuales",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto las define como pausas posibles y realistas cuando no es sencillo organizar vacaciones extensas.",
      tip: "No confundas una alternativa viable con una solución ideal o absoluta.",
      topics: ["details", "inference"],
    },
    {
      id: "per7-q6",
      prompt: "¿Qué rasgos vuelven atractivo al turismo de cercanía en escenarios inciertos?",
      options: [
        "La posibilidad de modificar planes con mayor flexibilidad",
        "La dependencia de vuelos costosos",
        "La necesidad de reservar con menos anticipación",
        "A y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto señala que esta modalidad reduce riesgos porque permite decidir con más flexibilidad y exige menos reserva anticipada.",
      tip: "Cuando el texto relaciona incertidumbre con menor riesgo, buscá opciones que apunten a flexibilidad y control.",
      topics: ["causeEffect", "details"],
    },
    {
      id: "per7-q7",
      prompt: "¿Qué quiere decir el texto cuando afirma que el turismo de cercanía está 'lejos de ser una opción menor'?",
      options: [
        "Que es una alternativa secundaria y poco valiosa",
        "Que no debe pensarse como una elección inferior por el hecho de ser cercana",
        "Que solo sirve cuando fracasan los viajes largos",
        "Que perdió todo impacto sobre las economías locales",
      ],
      correctOptionIndex: 1,
      explanation:
        "La frase rechaza la idea de que esta modalidad valga menos por no implicar grandes distancias.",
      tip: "No leas literalmente una expresión enfática si el sentido del párrafo apunta a corregir un prejuicio.",
      topics: ["vocabulary", "inference"],
      isTricky: true,
    },
    {
      id: "per7-q8",
      prompt: "¿Qué cambio cultural describe el texto en relación con el descanso?",
      options: [
        "Que descansar exige necesariamente una experiencia excepcional",
        "Que el descanso puede lograrse también interrumpiendo por un momento la rutina habitual",
        "Que la cercanía impide cualquier sensación de pausa",
        "Que solo los paisajes completamente nuevos permiten desconectar",
        "Que las escapadas cortas eliminan por completo la rutina",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto sostiene que para muchas personas descansar ya no depende de algo extraordinario, sino de abrir una pausa dentro de la vida cotidiana.",
      tip: "Buscá el matiz: el texto no elimina el deseo de novedad, pero relativiza su centralidad.",
      topics: ["inference", "conclusion"],
    },
    {
      id: "per7-q9",
      prompt: "¿Qué cambios menciona el texto en localidades próximas a grandes centros urbanos?",
      options: [
        "Reciben visitantes que antes no consideraban esos destinos",
        "Aparecen propuestas pensadas para estadías más cortas",
        "Desaparecen las actividades culturales y recreativas",
        "A y B",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto afirma que estos destinos ganan visitantes y desarrollan nuevas ofertas adaptadas a viajes más breves y frecuentes.",
      tip: "Cuando una pregunta junta dos efectos del mismo proceso, revisá si el texto confirma ambos.",
      topics: ["details"],
    },
    {
      id: "per7-q10",
      prompt: "¿Qué función cumple el párrafo sobre economías locales?",
      options: [
        "Mostrar que el turismo de cercanía impacta también en ingresos y emprendimientos de los destinos",
        "Negar que existan beneficios para pueblos o ciudades intermedias",
        "Demostrar que el turismo solo favorece a grandes cadenas internacionales",
        "Cerrar el texto antes de introducir cualquier dificultad",
      ],
      correctOptionIndex: 0,
      explanation:
        "Ese tramo amplía el foco desde la experiencia del viajero hacia sus efectos económicos sobre los lugares que reciben visitantes.",
      tip: "Pensá si el párrafo agrega una nueva dimensión del problema: en este caso, la dimensión local.",
      topics: ["structure", "tools"],
    },
    {
      id: "per7-q11",
      prompt: "En el texto, ¿qué significa que un viaje sea 'compatible con la vida cotidiana'?",
      options: [
        "Que pueda integrarse a tiempos, presupuesto y obligaciones reales",
        "Que deba repetirse todos los fines de semana",
        "Que ocurra siempre dentro del propio barrio",
        "Que no requiera ningún gasto económico",
      ],
      correctOptionIndex: 0,
      explanation:
        "La compatibilidad alude a la posibilidad concreta de realizar ese viaje sin desajustar por completo la organización cotidiana.",
      tip: "Traducí la expresión al contexto: no se refiere a cercanía pura, sino a viabilidad práctica.",
      topics: ["vocabulary"],
    },
    {
      id: "per7-q12",
      prompt: "¿Qué nuevas propuestas menciona el texto para destinos de cercanía?",
      options: [
        "Alojamiento",
        "Gastronomía",
        "Circuitos culturales y actividades al aire libre",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto enumera esos tipos de oferta como parte de la reorganización del mapa turístico en destinos próximos.",
      tip: "Si el párrafo enumera varias propuestas y la opción integradora coincide, suele ser la mejor respuesta.",
      topics: ["details"],
    },
    {
      id: "per7-q13",
      prompt: "¿Por qué la incertidumbre favorece al turismo de cercanía, según el texto?",
      options: [
        "Porque obliga a tomar siempre decisiones con un año de anticipación",
        "Porque reduce riesgos al depender menos de factores costosos o difíciles de controlar",
        "Porque elimina cualquier necesidad de planificación",
        "Porque vuelve innecesario el descanso",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto vincula la incertidumbre con el valor de opciones que permiten modificar planes y reducir exposición a pérdidas.",
      tip: "Buscá la relación entre incertidumbre y control sobre la decisión.",
      topics: ["causeEffect", "inference"],
    },
    {
      id: "per7-q14",
      prompt: "¿Cuál de estas afirmaciones contradice el texto?",
      options: [
        "El crecimiento del turismo de cercanía depende también de infraestructura y organización",
        "La llegada de visitantes puede generar oportunidades económicas para emprendimientos pequeños",
        "El aumento de visitantes garantiza siempre un desarrollo automático y equilibrado",
        "Los gobiernos locales pueden intentar promover un turismo sostenible",
      ],
      correctOptionIndex: 2,
      explanation:
        "El texto advierte explícitamente que ese crecimiento no siempre es automático ni equilibrado, y que requiere condiciones concretas.",
      tip: "Las opciones absolutas como 'siempre' o 'garantiza' merecen especial atención en textos matizados.",
      topics: ["inference"],
      isTricky: true,
    },
    {
      id: "per7-q15",
      prompt: "¿Sobre qué áreas puede presionar un aumento repentino de visitantes?",
      options: [
        "El transporte",
        "El abastecimiento",
        "La gestión de residuos",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El penúltimo párrafo enumera exactamente esos tres ámbitos como posibles puntos de presión para los destinos.",
      tip: "En preguntas de listado, comprobá que todos los elementos aparezcan en la misma parte del texto.",
      topics: ["details", "causeEffect"],
    },
    {
      id: "per7-q16",
      prompt: "¿Cómo avanza el argumento del texto?",
      options: [
        "Pasa de la redefinición del viaje a sus causas, impactos locales y desafíos de planificación",
        "Parte de estadísticas aeronáuticas y termina negando todo cambio cultural",
        "Se concentra solo en los costos de hoteles de lujo",
        "Compara dos países específicos y evita hablar del tiempo disponible",
        "Defiende exclusivamente los viajes internacionales",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto presenta la tendencia, explica por qué surge, muestra sus efectos económicos y cierra con sus desafíos.",
      tip: "Seguí el recorrido del texto párrafo por párrafo para detectar la secuencia argumentativa.",
      topics: ["structure"],
    },
    {
      id: "per7-q17",
      prompt: "¿Qué conclusión general ofrece el último párrafo?",
      options: [
        "Viajar solo vale si implica mucha distancia",
        "El turismo de cercanía refleja una nueva forma de equilibrar deseo, tiempo y posibilidades reales",
        "Las limitaciones económicas explican por completo cualquier elección turística",
        "La cercanía elimina el interés por conocer lugares nuevos",
      ],
      correctOptionIndex: 1,
      explanation:
        "El cierre afirma que esta tendencia no es solo una limitación, sino una manera distinta de articular deseos con condiciones concretas.",
      tip: "La conclusión correcta suele recuperar varios factores mencionados antes y sintetizarlos en una sola idea.",
      topics: ["conclusion", "mainIdea"],
    },
    {
      id: "per7-q18",
      prompt: "Según el cierre, ¿de qué depende ahora el valor del viaje para muchas personas?",
      options: [
        "De cuán lejos se llega",
        "De cuán bien se integra a la vida concreta",
        "De la flexibilidad y posibilidad real de hacerlo",
        "B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto dice que el viaje ya no vale solo por la distancia, sino por su integración con la vida real y sus condiciones efectivas de realización.",
      tip: "Cuando el cierre corrige una idea tradicional, buscá la opción que recoja ese nuevo criterio.",
      topics: ["conclusion", "inference"],
    },
    {
      id: "per7-q19",
      prompt: "¿Por qué muchas familias prefieren opciones más accesibles, según el texto?",
      options: [
        "Porque desean eliminar cualquier forma de planificación",
        "Porque buscan descansar sin comprometer una parte excesiva del presupuesto",
        "Porque rechazan cualquier destino natural cercano",
        "Porque los viajes largos ya no existen",
      ],
      correctOptionIndex: 1,
      explanation:
        "El factor económico se presenta como una razón importante para elegir alternativas que no tensionen demasiado el presupuesto familiar.",
      tip: "Prestá atención a expresiones como 'sin comprometer una parte excesiva': suelen definir el criterio de elección.",
      topics: ["details", "causeEffect"],
    },
    {
      id: "per7-q20",
      prompt: "¿Cómo debe entenderse la frase 'No prometen una desconexión total, pero sí una pausa posible'?",
      options: [
        "Como una crítica que niega cualquier utilidad al turismo de cercanía",
        "Como la idea de que estas salidas ofrecen un descanso realista, aunque no idealizado",
        "Como la prueba de que las personas ya no desean descansar",
        "Como una descripción exclusiva de viajes internacionales",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto no exagera los beneficios: presenta estas escapadas como un alivio viable dentro de condiciones concretas, no como una evasión absoluta.",
      tip: "Identificá el matiz entre una pausa suficiente y una desconexión perfecta.",
      topics: ["inference", "vocabulary"],
      isTricky: true,
    },
    {
      id: "per7-q21",
      prompt: "¿Qué busca un turismo sostenible, según el texto?",
      options: [
        "Generar ingresos",
        "No deteriorar el entorno",
        "No alterar por completo la vida cotidiana de los residentes",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El penúltimo párrafo define el turismo sostenible justamente como un equilibrio entre ingresos, entorno y vida local.",
      tip: "Si el texto da una definición compuesta, la respuesta correcta puede reunir sus tres partes.",
      topics: ["details", "conclusion"],
    },
    {
      id: "per7-q22",
      prompt: "¿Qué significa en el texto 'reorganizar el mapa turístico'?",
      options: [
        "Eliminar los destinos tradicionales del turismo",
        "Redirigir flujos y ofertas hacia localidades antes menos consideradas",
        "Reducir el turismo a un fenómeno exclusivamente urbano",
        "Sustituir todos los viajes por recorridos dentro del hogar",
      ],
      correctOptionIndex: 1,
      explanation:
        "La expresión alude a que nuevos destinos cercanos ganan peso en la circulación de visitantes y en la oferta turística disponible.",
      tip: "Interpretá la metáfora según el proceso que describe el párrafo, no de manera literal.",
      topics: ["vocabulary", "structure"],
    },
  ],
  PER8: [
    {
      id: "per8-q1",
      prompt: "¿Cuál es la idea principal del texto?",
      options: [
        "Las plataformas digitales dejaron de usarse de forma masiva",
        "La relación entre usuarios y plataformas se volvió más compleja y reflexiva con el tiempo",
        "La velocidad del servicio sigue siendo el único criterio relevante",
        "Las personas rechazaron por completo cualquier forma de consumo digital",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto muestra una transición desde la aceptación casi automática hacia una evaluación más crítica de costos, condiciones y control del usuario.",
      tip: "Buscá la transformación central de la relación entre consumidores y plataformas, no un detalle aislado.",
      topics: ["mainIdea", "conclusion"],
    },
    {
      id: "per8-q2",
      prompt: "¿Qué prometían inicialmente las plataformas digitales, según el texto?",
      options: [
        "Simplificar tareas que antes requerían más tiempo y esfuerzo",
        "Eliminar toda diferencia entre usuarios y empresas",
        "Reducir la necesidad de comparar precios",
        "Reemplazar por completo cualquier negocio físico",
        "Garantizar transparencia total desde el inicio",
      ],
      correctOptionIndex: 0,
      explanation:
        "El primer párrafo afirma que la expansión de las plataformas se apoyó en la promesa de resolver múltiples tareas con rapidez y comodidad.",
      tip: "Si la pregunta apunta al comienzo del texto, buscá cómo se describe la promesa original.",
      topics: ["details"],
    },
    {
      id: "per8-q3",
      prompt: "¿Qué actividades presenta el texto como ejemplos de tareas resueltas por plataformas?",
      options: [
        "Pedir comida",
        "Comprar productos",
        "Acceder a entretenimiento",
        "Resolver cualquier trámite estatal",
        "A, B y C",
      ],
      correctOptionIndex: 4,
      explanation:
        "El primer párrafo enumera esos tres usos concretos para mostrar la expansión cotidiana de las plataformas.",
      tip: "Verificá que todos los elementos de una combinación estén nombrados de forma explícita.",
      topics: ["details"],
    },
    {
      id: "per8-q4",
      prompt: "¿Cómo describe el texto la primera etapa de relación entre usuarios y plataformas?",
      options: [
        "Como un período de desconfianza general y rechazo",
        "Como una etapa de aceptación con pocas preguntas debido a la novedad y la eficiencia",
        "Como un momento en que los usuarios priorizaban la transparencia de datos sobre la rapidez",
        "Como una relación centrada en debates laborales y sociales desde el inicio",
      ],
      correctOptionIndex: 1,
      explanation:
        "El segundo párrafo afirma que al principio muchos usuarios aceptaron estas formas de consumo sin cuestionarlas demasiado.",
      tip: "Prestá atención a los marcadores temporales como 'durante la primera etapa'.",
      topics: ["details", "structure"],
    },
    {
      id: "per8-q5",
      prompt: "¿Qué costos menos evidentes comenzaron a hacerse visibles con el tiempo?",
      options: [
        "Comisiones elevadas, precios variables y menor transparencia",
        "La desaparición total del entretenimiento digital",
        "La imposibilidad de acceder a cualquier servicio desde el celular",
        "La prohibición de cancelar pedidos",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto menciona esos problemas como parte del cambio de percepción de los usuarios frente a las plataformas.",
      tip: "Cuando el texto enumera problemas concretos, no reemplaces esos datos por exageraciones.",
      topics: ["details"],
    },
    {
      id: "per8-q6",
      prompt: "Además de la rapidez, ¿qué empezó a importar más en la evaluación de una plataforma?",
      options: [
        "La claridad sobre cuánto cuesta",
        "Las condiciones bajo las que opera",
        "El margen de control que conserva el usuario",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El cuarto párrafo dice que ya no basta con la velocidad: también cuentan la información clara, las condiciones y el control del usuario.",
      tip: "Si el texto añade varios criterios nuevos a uno anterior, la respuesta correcta puede integrarlos.",
      topics: ["details", "conclusion"],
    },
    {
      id: "per8-q7",
      prompt: "¿Qué aclara el texto al decir que este cambio de percepción no implica un rechazo general?",
      options: [
        "Que los usuarios siguen valorando la utilidad de las plataformas, aunque las evalúan con más atención",
        "Que las plataformas dejaron de recibir críticas públicas",
        "Que la personalización resolvió todos los conflictos",
        "Que la costumbre volvió innecesaria cualquier comparación",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto no describe un abandono masivo, sino una relación más exigente y menos automática.",
      tip: "Buscá el matiz entre seguir usando algo y hacerlo sin cuestionamientos.",
      topics: ["inference", "details"],
    },
    {
      id: "per8-q8",
      prompt: "¿Qué matiz introduce el texto sobre la personalización de la experiencia?",
      options: [
        "Que siempre responde exclusivamente a necesidades reales del usuario",
        "Que puede resultar cómoda, pero también generar dudas sobre cómo orienta las decisiones",
        "Que ya no tiene ningún peso dentro de las plataformas",
        "Que solo importa para servicios de entretenimiento",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto plantea una tensión: la personalización ofrece comodidad, pero también despierta preguntas sobre su capacidad de dirigir decisiones.",
      tip: "En preguntas matizadas, evitá opciones totalmente positivas o totalmente negativas si el texto combina ambas dimensiones.",
      topics: ["inference", "details"],
      isTricky: true,
    },
    {
      id: "per8-q9",
      prompt: "¿Qué elementos compara hoy con mayor frecuencia un usuario, según el texto?",
      options: [
        "Precios",
        "Tiempos de entrega",
        "Opiniones de otros usuarios",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto afirma que hoy es más común comparar distintos aspectos del servicio antes de elegir una plataforma.",
      tip: "Si el párrafo enumera varios criterios de comparación, revisá si la opción integradora coincide con ellos.",
      topics: ["details"],
    },
    {
      id: "per8-q10",
      prompt: "¿Qué efecto tiene la pérdida del 'efecto novedad'?",
      options: [
        "Las plataformas vuelven a juzgarse solo por ser tecnológicas",
        "Empiezan a evaluarse con criterios más amplios como calidad, confiabilidad y costo razonable",
        "Los usuarios dejan automáticamente de utilizarlas",
        "La innovación tecnológica pierde toda relevancia social",
        "Las empresas dejan de competir entre sí",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto explica que cuando la tecnología deja de ser novedad, pasa a ser evaluada como un servicio concreto.",
      tip: "No confundas el fin del entusiasmo inicial con un rechazo total de la tecnología.",
      topics: ["causeEffect", "structure"],
    },
    {
      id: "per8-q11",
      prompt: "¿Qué dimensión adicional de debate creció alrededor de las plataformas?",
      options: [
        "La discusión sobre condiciones laborales y sociales detrás de su eficiencia",
        "La idea de que ya no usan datos personales",
        "La desaparición del trabajo humano en estos servicios",
        "La eliminación de cualquier sistema de calificación",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto destaca que la eficiencia de algunas plataformas empezó a discutirse también por sus efectos laborales y sociales.",
      tip: "Buscá qué tema deja de ser invisible a medida que el debate público se amplía.",
      topics: ["details", "inference"],
    },
    {
      id: "per8-q12",
      prompt: "¿Qué condiciones menciona el texto respecto de muchos trabajadores de plataformas?",
      options: [
        "Reglas rígidas",
        "Sistemas de calificación exigentes",
        "Ingresos inestables",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto enumera esas tres condiciones para mostrar que la eficiencia visible puede apoyarse en costos laborales poco visibles.",
      tip: "Revisá si los tres elementos aparecen juntos dentro del mismo pasaje del texto.",
      topics: ["details"],
    },
    {
      id: "per8-q13",
      prompt: "En el texto, ¿qué significa 'ecosistema digital'?",
      options: [
        "Un entorno natural modificado por la tecnología",
        "El conjunto de plataformas, prácticas y relaciones de consumo que organizan servicios digitales",
        "Un sistema exclusivo de redes sociales",
        "Una base de datos estatal de usuarios",
      ],
      correctOptionIndex: 1,
      explanation:
        "La expresión se usa para nombrar el conjunto articulado de servicios y decisiones que rodean el consumo digital.",
      tip: "Interpretá el término según el campo temático del texto, no por su sentido literal fuera de contexto.",
      topics: ["vocabulary"],
    },
    {
      id: "per8-q14",
      prompt: "¿Qué función cumple el párrafo sobre programas de beneficios y recomendaciones personalizadas?",
      options: [
        "Mostrar que las empresas también actúan para retener usuarios y reforzar dependencia",
        "Negar que exista competencia entre plataformas",
        "Probar que la personalización ya no influye en nadie",
        "Cerrar el texto con una defensa de la fidelidad automática",
      ],
      correctOptionIndex: 0,
      explanation:
        "Ese párrafo introduce la tensión entre empresas que buscan retener usuarios y consumidores que intentan recuperar capacidad de decisión.",
      tip: "Pensá qué conflicto central agrega ese párrafo al argumento.",
      topics: ["structure", "tools"],
    },
    {
      id: "per8-q15",
      prompt: "¿Qué mecanismos usan las plataformas para conservar la fidelidad de sus usuarios?",
      options: [
        "Programas de beneficios",
        "Recomendaciones personalizadas",
        "Sistemas que dificultan abandonar el servicio",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto menciona esos tres recursos como parte de la estrategia de retención de las empresas.",
      tip: "Si una pregunta apunta a estrategias empresariales, distinguí entre lo que hace el usuario y lo que hace la plataforma.",
      topics: ["details"],
    },
    {
      id: "per8-q16",
      prompt: "¿Cómo entiende el texto la relación actual entre usuarios y plataformas?",
      options: [
        "Como una negociación constante donde la conveniencia ya no basta por sí sola",
        "Como una adhesión automática basada solo en la costumbre",
        "Como un rechazo general a toda forma de intermediación digital",
        "Como una relación definida únicamente por la novedad tecnológica",
      ],
      correctOptionIndex: 0,
      explanation:
        "El cierre presenta la experiencia actual como una negociación en la que el usuario pesa mejor lo que gana y lo que cede.",
      tip: "La conclusión correcta suele retomar una fórmula fuerte del último párrafo.",
      topics: ["conclusion", "mainIdea"],
    },
    {
      id: "per8-q17",
      prompt: "¿Qué significa que la experiencia digital se volvió 'más madura y menos ingenua'?",
      options: [
        "Que los usuarios rechazan toda innovación tecnológica",
        "Que los usuarios evalúan con más conciencia condiciones, costos y mecanismos de influencia",
        "Que las plataformas dejaron de personalizar servicios",
        "Que la rapidez ya no tiene ningún valor",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto no habla de rechazo total, sino de una mirada más consciente y menos automática sobre cómo funcionan estos servicios.",
      tip: "No confundas madurez crítica con abandono o rechazo absoluto.",
      topics: ["vocabulary", "conclusion"],
      isTricky: true,
    },
    {
      id: "per8-q18",
      prompt: "¿Qué cambió en la forma de elegir una plataforma?",
      options: [
        "Se elige solo por costumbre",
        "Se comparan opciones",
        "Se observan con mayor atención las condiciones del servicio",
        "B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto señala que la elección se volvió menos automática porque hoy se comparan alternativas y se observan mejor sus condiciones.",
      tip: "Buscá las conductas nuevas que el texto opone a la elección por hábito.",
      topics: ["details", "structure"],
    },
    {
      id: "per8-q19",
      prompt: "¿Para qué sirven los ejemplos del inicio como pedir comida o contratar un viaje?",
      options: [
        "Para mostrar el alcance cotidiano y la comodidad inicial asociada a las plataformas",
        "Para demostrar que todos los servicios digitales son idénticos",
        "Para sostener que la crítica actual es injustificada",
        "Para probar que las plataformas eliminan cualquier esfuerzo humano",
        "Para afirmar que la personalización ya estaba cuestionada desde el principio",
      ],
      correctOptionIndex: 0,
      explanation:
        "Los ejemplos iniciales buscan mostrar por qué estas plataformas se expandieron tan rápido en la vida cotidiana.",
      tip: "Pensá qué idea general ilustran los ejemplos, no solo qué acciones enumeran.",
      topics: ["tools"],
    },
    {
      id: "per8-q20",
      prompt: "¿Por qué el texto dice que las plataformas dejan de percibirse solo como innovaciones admirables?",
      options: [
        "Porque dejan de existir en el mercado",
        "Porque empiezan a juzgarse como servicios concretos con costos, condiciones y efectos",
        "Porque ya no ofrecen ninguna utilidad práctica",
        "Porque se vuelven irrelevantes para los usuarios frecuentes",
      ],
      correctOptionIndex: 1,
      explanation:
        "A medida que la novedad se desgasta, lo central ya no es la fascinación tecnológica sino la calidad real del servicio.",
      tip: "Identificá el pasaje donde el texto cambia del entusiasmo inicial a la evaluación concreta.",
      topics: ["inference", "causeEffect"],
    },
    {
      id: "per8-q21",
      prompt: "Según el cierre, ¿qué valor sigue siendo importante pero ya no alcanza por sí solo?",
      options: [
        "La conveniencia",
        "La opacidad en el uso de datos",
        "La costumbre de usar siempre la misma aplicación",
        "Ninguna de las anteriores",
      ],
      correctOptionIndex: 0,
      explanation:
        "La última parte del texto dice explícitamente que la conveniencia sigue siendo valiosa, pero ya no basta por sí sola.",
      tip: "Buscá la palabra o expresión que el cierre conserva, aunque le quite suficiencia.",
      topics: ["details", "conclusion"],
    },
    {
      id: "per8-q22",
      prompt: "Antes de este cambio de percepción, ¿por qué muchos consumidores elegían una plataforma?",
      options: [
        "Porque parecía dominante en su sector o por simple costumbre",
        "Porque conocían en detalle sus políticas de datos",
        "Porque tomaban la decisión principalmente por razones laborales",
        "Porque rechazaban la personalización desde el principio",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto describe una elección más automática, guiada por hábito o por la posición dominante de ciertas plataformas.",
      tip: "Compará la conducta pasada con la actual para detectar qué cambió.",
      topics: ["details"],
    },
    {
      id: "per8-q23",
      prompt: "¿Qué aclara el texto sobre la sensibilidad de los usuarios frente a cuestiones laborales y sociales?",
      options: [
        "Que todos los usuarios deciden exclusivamente en función de esos factores",
        "Que el tema pasó a formar parte de la imagen social de estas empresas, aunque no determine siempre la decisión",
        "Que esas cuestiones fueron resueltas por completo",
        "Que solo importan en servicios de entretenimiento",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto matiza el punto: no todos eligen por ese motivo, pero la discusión dejó de ser invisible y ya influye en la percepción social.",
      tip: "Prestá atención a las fórmulas intermedias: 'no todos', 'aunque', 'pasó a formar parte'.",
      topics: ["inference", "details"],
      isTricky: true,
    },
    {
      id: "per8-q24",
      prompt: "¿Con qué criterios más amplios empiezan a juzgarse las plataformas cuando pierden el efecto novedad?",
      options: [
        "Calidad",
        "Confiabilidad",
        "Costo razonable",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto enumera esos criterios para mostrar que la evaluación se vuelve más concreta y menos fascinada por la innovación.",
      tip: "Si el texto lista varios criterios equivalentes, la opción integradora puede ser la correcta.",
      topics: ["details"],
    },
    {
      id: "per8-q25",
      prompt: "¿Qué resume mejor el sentido global del texto?",
      options: [
        "Las plataformas dejaron de ser útiles para la mayoría de las personas",
        "Los usuarios pasaron de una adhesión más ingenua a una relación de evaluación, comparación y negociación",
        "La personalización resolvió de manera definitiva los problemas del consumo digital",
        "La innovación tecnológica ya no influye en ninguna decisión cotidiana",
      ],
      correctOptionIndex: 1,
      explanation:
        "Esa opción integra la evolución central que describe el texto: del entusiasmo inicial a una experiencia más crítica y consciente.",
      tip: "La mejor síntesis debe unir el comienzo y el cierre del texto en una sola transformación.",
      topics: ["mainIdea", "conclusion"],
    },
  ],
  PER9: [
    {
      id: "per9-q1",
      prompt: "¿Cuál es la idea principal del texto?",
      options: [
        "La desigualdad urbana depende únicamente del ingreso y del transporte",
        "La calidad concreta de la vivienda se volvió una dimensión central y muchas veces silenciosa de la desigualdad urbana",
        "Las políticas de vivienda ya resolvieron los principales problemas de habitabilidad",
        "La ubicación dejó por completo de influir en la experiencia urbana",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto sostiene que no alcanza con tener vivienda: importan sus condiciones reales y cómo ellas amplían o reducen otras desigualdades.",
      tip: "La idea principal debe captar el desplazamiento del foco desde lo visible hacia una desigualdad más silenciosa.",
      topics: ["mainIdea", "conclusion"],
    },
    {
      id: "per9-q2",
      prompt: "¿Qué funciones dice el texto que hoy puede cumplir una vivienda?",
      options: [
        "Trabajo",
        "Estudio",
        "Cuidado, ocio y socialización",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto señala que el hogar ya no es solo un lugar de residencia y descanso, sino un espacio de múltiples funciones superpuestas.",
      tip: "Revisá la enumeración del segundo párrafo: ahí aparece el cambio de definición del hogar.",
      topics: ["details"],
    },
    {
      id: "per9-q3",
      prompt: "¿Qué características de la vivienda ganan peso en el texto?",
      options: [
        "La ventilación, la luz natural, el ruido, los materiales y la conectividad",
        "Solo la cantidad de adornos o muebles decorativos",
        "El color exterior de la fachada y el estilo arquitectónico",
        "Exclusivamente la distancia al centro comercial más cercano",
        "La antigüedad del edificio como único criterio",
      ],
      correctOptionIndex: 0,
      explanation:
        "El tercer párrafo enumera varios rasgos concretos que pasan a influir sobre descanso, productividad y bienestar.",
      tip: "No reemplaces condiciones de habitabilidad por atributos estéticos que el texto no menciona.",
      topics: ["details"],
    },
    {
      id: "per9-q4",
      prompt: "¿Cómo explica el texto que dos personas con salarios parecidos puedan experimentar condiciones de vida muy distintas?",
      options: [
        "Porque el ingreso determina por sí solo la calidad del hogar",
        "Porque la funcionalidad y calidad del espacio habitable pueden variar mucho aunque el salario sea similar",
        "Porque las diferencias de vivienda desaparecen cuando el barrio es el mismo",
        "Porque la desigualdad urbana se reduce siempre a decisiones individuales",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto destaca que la desigualdad no siempre se ve en el ingreso: también aparece en el espacio disponible, el ruido, la conectividad o la funcionalidad del hogar.",
      tip: "Buscá el contraste entre 'salarios parecidos' y 'condiciones de vida distintas'.",
      topics: ["causeEffect", "inference"],
    },
    {
      id: "per9-q5",
      prompt: "¿Qué elementos menciona el texto como factores que pueden afectar el descanso, la productividad o la salud mental?",
      options: [
        "La ventilación",
        "La luz natural",
        "El nivel de ruido",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "Esos elementos aparecen de forma explícita en el tercer párrafo como condiciones que inciden en la vida cotidiana dentro del hogar.",
      tip: "Cuando el texto enumera factores físicos del espacio, revisá si la opción integradora coincide exactamente con ellos.",
      topics: ["details"],
    },
    {
      id: "per9-q6",
      prompt: "¿Cómo se expande el argumento del texto a lo largo de sus párrafos?",
      options: [
        "Parte del interior de la vivienda y luego lo conecta con oportunidades, políticas públicas y experiencia urbana",
        "Se limita a comparar materiales de construcción sin considerar efectos sociales",
        "Abandona rápido la vivienda para concentrarse solo en el transporte",
        "Describe únicamente barrios periféricos y evita generalizaciones",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto va del espacio doméstico a sus consecuencias educativas, laborales, políticas y urbanas en sentido amplio.",
      tip: "Pensá cómo el texto va ampliando escala: del hogar al barrio, a las trayectorias y a la ciudad.",
      topics: ["structure"],
    },
    {
      id: "per9-q7",
      prompt: "¿Qué busca subrayar la expresión 'infraestructura íntima'?",
      options: [
        "Que la vivienda es un lujo estrictamente privado sin consecuencias colectivas",
        "Que ciertas condiciones del hogar, aunque parezcan íntimas, tienen efectos públicos y sociales",
        "Que las obras públicas dejaron de ser importantes frente a la decoración interior",
        "Que solo importa el tamaño de la vivienda y no su relación con el entorno",
      ],
      correctOptionIndex: 1,
      explanation:
        "La expresión sirve para mostrar que la desigualdad también se organiza dentro de los hogares y que eso repercute en trayectorias sociales más amplias.",
      tip: "No confundas 'íntima' con 'irrelevante para lo público': el texto justamente discute esa separación.",
      topics: ["vocabulary", "conclusion"],
      isTricky: true,
    },
    {
      id: "per9-q8",
      prompt: "¿Cómo describe el texto la acumulación de desventajas asociadas a una vivienda incómoda?",
      options: [
        "Dificulta el descanso",
        "Afecta la concentración",
        "Perjudica el rendimiento laboral o educativo",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El cuarto y quinto párrafo muestran una cadena de efectos donde una condición espacial doméstica termina afectando oportunidades futuras.",
      tip: "Cuando el texto presenta una secuencia causal, observá si la respuesta integra varios eslabones de esa cadena.",
      topics: ["causeEffect", "details"],
    },
    {
      id: "per9-q9",
      prompt: "¿Qué aclara el texto sobre la ubicación de la vivienda?",
      options: [
        "Que dejó de importar por completo",
        "Que debe pensarse junto con las condiciones internas del hogar",
        "Que solo importa para el valor inmobiliario",
        "Que resuelve automáticamente la posibilidad de estudiar o trabajar",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto insiste en que no alcanza con una buena ubicación si el interior del hogar no permite vivir, estudiar o trabajar razonablemente.",
      tip: "Buscá las frases donde el texto articula dos variables en vez de oponerlas de forma absoluta.",
      topics: ["details", "inference"],
    },
    {
      id: "per9-q10",
      prompt: "¿Qué se puede inferir sobre la relación entre privacidad y vida pública a partir del texto?",
      options: [
        "Que la privacidad ya no existe en ningún hogar urbano",
        "Que problemas antes vistos como íntimos pueden tener efectos sobre educación, trabajo y salud colectiva",
        "Que lo público no tiene ninguna relación con lo que ocurre dentro de la vivienda",
        "Que las viviendas bien conectadas no producen desigualdad",
        "Que la vida familiar dejó de importar en la ciudad",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto muestra que ciertas condiciones del espacio doméstico generan consecuencias que exceden la esfera privada.",
      tip: "Inferí a partir del pasaje donde el texto amplía efectos íntimos hacia trayectorias y condiciones colectivas.",
      topics: ["inference", "conclusion"],
    },
    {
      id: "per9-q11",
      prompt: "¿En qué solían concentrarse muchas políticas de vivienda, según el texto?",
      options: [
        "En la cantidad de unidades construidas y la formalización del acceso",
        "En la salud mental doméstica como prioridad exclusiva",
        "En la decoración y el mobiliario de los hogares",
        "En reducir únicamente los desplazamientos al trabajo",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto señala que tradicionalmente muchas políticas se enfocaron en cantidad y acceso formal, dejando menos atendida la habitabilidad concreta.",
      tip: "Prestá atención al contraste entre 'tradicionalmente' y 'hoy parece necesario'.",
      topics: ["details", "structure"],
    },
    {
      id: "per9-q12",
      prompt: "¿Qué aspectos propone incorporar con más fuerza a las políticas de vivienda?",
      options: [
        "Habitabilidad",
        "Infraestructura interna",
        "Adecuación real de los espacios a necesidades actuales",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto plantea que ya no basta con contar unidades o formalizar acceso: también hace falta pensar cómo se habita efectivamente.",
      tip: "Buscá qué nuevas preguntas agrega el texto a las políticas tradicionales.",
      topics: ["details", "conclusion"],
    },
    {
      id: "per9-q13",
      prompt: "¿Cuál de estas afirmaciones contradice el texto?",
      options: [
        "Una zona bien conectada puede no alcanzar si la vivienda es poco funcional",
        "Una vivienda adecuada puede perder valor práctico si obliga a desplazamientos largos",
        "Vivir en un barrio bien conectado basta por sí solo para estudiar, trabajar y convivir razonablemente",
        "La experiencia urbana depende de la relación entre hogar, barrio y oportunidades",
      ],
      correctOptionIndex: 2,
      explanation:
        "El texto dice explícitamente que la conectividad del barrio no alcanza si el espacio habitable no permite desarrollar la vida cotidiana de forma razonable.",
      tip: "Las opciones que convierten un factor importante en condición suficiente suelen ser engañosas.",
      topics: ["inference"],
      isTricky: true,
    },
    {
      id: "per9-q14",
      prompt: "En el contexto del texto, ¿qué se entiende por 'habitabilidad'?",
      options: [
        "La posibilidad real de usar la vivienda de forma adecuada para necesidades contemporáneas",
        "La cantidad de personas inscriptas formalmente en una propiedad",
        "La ubicación de la vivienda dentro de un mapa catastral",
        "El prestigio simbólico del barrio donde se encuentra",
      ],
      correctOptionIndex: 0,
      explanation:
        "Habitabilidad alude a qué tan apto es el espacio para sostener descanso, estudio, trabajo, convivencia y bienestar.",
      tip: "Definí el término por su función en el texto, no por un sentido legal o administrativo.",
      topics: ["vocabulary"],
    },
    {
      id: "per9-q15",
      prompt: "¿Por qué el texto describe estas desigualdades como 'silenciosas'?",
      options: [
        "Porque ya no afectan a muchas personas",
        "Porque no siempre ocupan el centro del debate ni se advierten fácilmente desde afuera",
        "Porque solo aparecen en barrios sin transporte público",
        "Porque se miden con absoluta precisión en todas las estadísticas",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto aclara que estas desigualdades no siempre se ven en fachadas o indicadores generales, aunque moldean la vida diaria.",
      tip: "Buscá la explicación explícita del adjetivo en el penúltimo tramo del texto.",
      topics: ["causeEffect", "vocabulary"],
    },
    {
      id: "per9-q16",
      prompt: "¿Qué factores pueden hacer que una vivienda pierda parte de su valor práctico, aun si está mejor resuelta en su interior?",
      options: [
        "Largos desplazamientos diarios",
        "Escaso acceso a servicios en el entorno",
        "Abundante luz natural",
        "A y B",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto señala que una buena vivienda puede perder valor práctico si está lejos de servicios, escuelas, transporte o si exige viajes interminables.",
      tip: "Prestá atención al giro 'a la inversa': allí el texto introduce un matiz importante.",
      topics: ["details", "causeEffect"],
    },
    {
      id: "per9-q17",
      prompt: "¿Qué conclusión resume mejor el cierre del texto?",
      options: [
        "La ciudad solo distribuye servicios externos y no condiciones de habitabilidad",
        "Pensar la ciudad hoy exige mirar también lo que ocurre dentro de las viviendas",
        "La desigualdad urbana puede explicarse solo por la distancia entre barrios",
        "La calidad de la vivienda dejó de tener relación con la vida social",
      ],
      correctOptionIndex: 1,
      explanation:
        "El cierre insiste en que la ciudad distribuye no solo infraestructuras externas, sino también posibilidades desiguales de habitar con dignidad.",
      tip: "La conclusión correcta debe recuperar el desplazamiento del foco hacia el interior del hogar.",
      topics: ["conclusion", "mainIdea"],
    },
    {
      id: "per9-q18",
      prompt: "¿Qué dice el texto sobre la visibilidad de estas desigualdades?",
      options: [
        "Que aparecen necesariamente en la fachada de los edificios",
        "Que no siempre se reflejan a simple vista ni en estadísticas generales",
        "Que solo se detectan en informes de mercado inmobiliario",
        "Que son visibles únicamente cuando hay hacinamiento extremo",
        "Que resultan evidentes para cualquier observador ocasional",
      ],
      correctOptionIndex: 1,
      explanation:
        "El penúltimo párrafo subraya justamente que estas desigualdades suelen pasar desapercibidas aunque tengan efectos intensos.",
      tip: "No conviertas una desigualdad silenciosa en una desigualdad siempre evidente.",
      topics: ["details"],
    },
    {
      id: "per9-q19",
      prompt: "Según el texto, ¿de qué depende la experiencia urbana?",
      options: [
        "Del interior del hogar",
        "Del barrio y su entorno",
        "De las oportunidades que ese entorno habilita o restringe",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto afirma que la experiencia urbana se configura en la relación entre esas tres dimensiones, no en una sola variable.",
      tip: "Si el autor insiste en una relación entre factores, desconfiá de respuestas que aíslen solo uno.",
      topics: ["conclusion", "details"],
    },
    {
      id: "per9-q20",
      prompt: "¿Qué función cumple la expresión 'A la inversa' en el tramo final del texto?",
      options: [
        "Introduce la idea de que una vivienda adecuada también puede perder valor si el entorno es deficitario",
        "Niega todo lo dicho antes sobre la importancia del interior del hogar",
        "Muestra que la ubicación deja de importar por completo",
        "Cierra el texto con una definición legal de vivienda",
      ],
      correctOptionIndex: 0,
      explanation:
        "La expresión sirve para invertir el ejemplo anterior y mostrar que la relación entre vivienda y entorno funciona en ambos sentidos.",
      tip: "Observá cómo el texto construye simetrías y contrapesos entre interior y entorno.",
      topics: ["structure", "inference"],
      isTricky: true,
    },
    {
      id: "per9-q21",
      prompt: "¿Para qué utiliza el texto la cadena 'mal descanso - menor concentración - peor rendimiento'?",
      options: [
        "Para ilustrar cómo una condición doméstica puede producir efectos sociales más amplios",
        "Para afirmar que el descanso es más importante que cualquier otra variable",
        "Para negar la influencia del espacio sobre la vida cotidiana",
        "Para describir un problema exclusivamente médico",
      ],
      correctOptionIndex: 0,
      explanation:
        "La secuencia muestra el mecanismo por el cual una desigualdad aparentemente doméstica termina afectando educación, trabajo y oportunidades futuras.",
      tip: "Pensá qué demuestra la cadena causal dentro del argumento general.",
      topics: ["tools", "causeEffect"],
    },
    {
      id: "per9-q22",
      prompt: "¿Qué consecuencias públicas puede tener una vivienda que no permita estudiar, trabajar o descansar apropiadamente?",
      options: [
        "Afectar trayectorias educativas",
        "Impactar la inserción laboral",
        "Incidir en la salud colectiva",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto amplía los efectos del espacio doméstico hacia dimensiones claramente públicas y colectivas.",
      tip: "Cuando el texto discute la frontera entre privado y público, revisá si la opción reúne varios efectos sociales.",
      topics: ["details", "conclusion"],
    },
    {
      id: "per9-q23",
      prompt: "¿Qué se puede inferir del caso de dos personas con salarios parecidos?",
      options: [
        "Que la igualdad de ingresos garantiza experiencias urbanas equivalentes",
        "Que el ingreso no agota las formas posibles de desigualdad",
        "Que el salario deja de tener importancia en cualquier análisis urbano",
        "Que la calidad del espacio doméstico depende solo de preferencias personales",
        "Que la vivienda amplia siempre se consigue con el mismo ingreso",
      ],
      correctOptionIndex: 1,
      explanation:
        "Ese ejemplo sirve para mostrar que existen desigualdades relevantes que no se captan mirando solo el salario.",
      tip: "Inferí la idea general que el ejemplo intenta probar dentro del argumento.",
      topics: ["inference"],
    },
    {
      id: "per9-q24",
      prompt: "¿Qué significa en el texto la 'adecuación real de los espacios'?",
      options: [
        "Que el hogar responda de verdad a usos contemporáneos como trabajar, estudiar y convivir",
        "Que la vivienda esté valuada por encima del precio promedio del mercado",
        "Que el edificio tenga certificaciones estéticas reconocidas",
        "Que el barrio cuente con comercios de lujo",
      ],
      correctOptionIndex: 0,
      explanation:
        "La expresión apunta a si el espacio resulta efectivamente apto para las necesidades actuales de la vida cotidiana.",
      tip: "No confundas adecuación funcional con valor económico o prestigio.",
      topics: ["vocabulary"],
    },
    {
      id: "per9-q25",
      prompt: "¿Qué cambio plantea el texto sobre la idea de privacidad?",
      options: [
        "Que la privacidad dejó de tener cualquier valor social",
        "Que lo que parecía quedar dentro de la esfera íntima muestra consecuencias públicas más visibles",
        "Que la privacidad solo importa en viviendas grandes",
        "Que los problemas del hogar deben analizarse únicamente como asuntos familiares",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto explica que ciertas condiciones íntimas del hogar ya no pueden pensarse como puramente privadas por sus efectos sobre educación, trabajo y salud.",
      tip: "Prestá atención a cómo el texto desplaza un problema desde lo íntimo hacia lo público sin negar la intimidad.",
      topics: ["inference", "conclusion"],
      isTricky: true,
    },
    {
      id: "per9-q26",
      prompt: "Según el cierre, ¿qué distribuye también la ciudad de manera desigual?",
      options: [
        "Distancias",
        "Servicios y oportunidades",
        "Condiciones para habitar con dignidad",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "La última parte del texto afirma que la ciudad organiza servicios y oportunidades, pero también reparte de manera desigual condiciones de habitabilidad.",
      tip: "La mejor respuesta del cierre suele reunir varios elementos ya conectados por el autor.",
      topics: ["conclusion", "details"],
    },
    {
      id: "per9-q27",
      prompt: "¿Qué resume mejor el sentido global del texto?",
      options: [
        "La vivienda debe analizarse solo como un bien material privado",
        "La desigualdad urbana incluye también las condiciones concretas desde las que se vive, estudia, trabaja y descansa",
        "El transporte explica por sí solo toda diferencia entre hogares",
        "Las políticas de vivienda actuales ya incorporan plenamente la habitabilidad",
      ],
      correctOptionIndex: 1,
      explanation:
        "La síntesis correcta retoma el eje del texto: la vivienda no es solo posesión o ubicación, sino una infraestructura cotidiana que condiciona la vida social.",
      tip: "Para cerrar, buscá la opción que articule hogar, desigualdad y vida cotidiana en una misma idea.",
      topics: ["mainIdea", "conclusion"],
    },
  ],
  PER10: [
    {
      id: "per10-q1",
      prompt: "¿Cuál es la idea principal del texto?",
      options: [
        "El consumo latinoamericano reciente puede entenderse solo como una caída del gasto",
        "La incertidumbre económica transforma el consumo en una práctica estratégica de administración del riesgo",
        "La inflación afecta a todos los países de la región de manera idéntica",
        "La planificación familiar desapareció por completo en América Latina",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto insiste en que el cambio no es solo cuánto se gasta, sino cómo se decide, se compara, se posterga y se administra el riesgo cotidiano.",
      tip: "La idea principal debe captar la transformación de la lógica del consumo, no solo su resultado material.",
      topics: ["mainIdea", "conclusion"],
    },
    {
      id: "per10-q2",
      prompt: "¿Por qué el texto considera simplificador interpretar este proceso solo como una reducción del gasto?",
      options: [
        "Porque el gasto en la región creció de forma estable",
        "Porque también cambian la lógica de decisión, los tiempos de compra y la gestión de la incertidumbre",
        "Porque el consumo dejó de relacionarse con necesidades materiales",
        "Porque las familias ya no comparan precios ni promociones",
        "Porque la región superó la volatilidad económica",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto reconoce ajustes materiales, pero sostiene que lo más importante es el cambio en la forma de decidir bajo incertidumbre.",
      tip: "Cuando el texto rechaza una explicación única, buscá qué dimensión adicional propone.",
      topics: ["inference", "conclusion"],
    },
    {
      id: "per10-q3",
      prompt: "¿Cómo describe el texto la fragmentación del consumo?",
      options: [
        "Compras más pequeñas",
        "Compras repetidas",
        "Compras ajustables según el contexto",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto define la fragmentación precisamente como el reemplazo de compras amplias por adquisiciones pequeñas, repetidas y ajustables.",
      tip: "Revisá si la opción integradora reproduce la definición que el texto da casi literalmente.",
      topics: ["details"],
    },
    {
      id: "per10-q4",
      prompt: "¿Qué efecto tiene esa fragmentación sobre los comercios?",
      options: [
        "Enfrentan una demanda más volátil y sensible a cambios puntuales",
        "Reciben una demanda más estable y previsible que antes",
        "Dejan de necesitar administrar inventarios",
        "Pueden fijar precios sin atender al comportamiento del consumidor",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto explica que las compras en tandas pequeñas vuelven más complejas las estrategias de abastecimiento y precios.",
      tip: "Buscá cómo el texto pasa de la conducta de los hogares al funcionamiento del sistema económico.",
      topics: ["causeEffect", "details"],
    },
    {
      id: "per10-q5",
      prompt: "¿Qué cambio produce esta nueva lógica en la temporalidad doméstica?",
      options: [
        "Libera tiempo para actividades recreativas sin costo",
        "Traslada parte del tiempo familiar a comparar promociones, revisar aplicaciones y reformular compras",
        "Vuelve innecesario controlar precios con frecuencia",
        "Reduce la atención que los hogares prestan al entorno económico",
        "Elimina la carga mental asociada al consumo",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto indica que adaptarse a la incertidumbre consume tiempo y energía mental, porque obliga a revisar decisiones con más frecuencia.",
      tip: "No pienses solo en dinero: el texto también analiza cómo cambia el uso del tiempo.",
      topics: ["details", "causeEffect"],
    },
    {
      id: "per10-q6",
      prompt: "¿Sobre qué bases podía construirse más lentamente la lealtad hacia ciertas marcas en períodos de estabilidad?",
      options: [
        "Confianza",
        "Costumbre",
        "Identidad asociada a una empresa",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto enumera esos tres elementos para contrastarlos con la fragilidad actual de la lealtad cuando el precio gana centralidad.",
      tip: "Compará el escenario estable con el incierto para detectar qué vínculos se debilitan.",
      topics: ["details"],
    },
    {
      id: "per10-q7",
      prompt: "¿Qué ocurre con el crédito cuando aumentan la incertidumbre de precios, ingresos o tasas?",
      options: [
        "Se vuelve necesariamente más conveniente para todos los hogares",
        "Puede pasar de ser un recurso planificable a percibirse como un riesgo difícil de controlar",
        "Pierde cualquier relación con la planificación del gasto",
        "Desaparece por completo como herramienta de consumo",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto no dice que el crédito desaparezca, sino que en contextos inciertos puede ser vivido como algo más riesgoso.",
      tip: "Prestá atención a cómo cambia la percepción de una misma herramienta según el contexto.",
      topics: ["inference", "causeEffect"],
    },
    {
      id: "per10-q8",
      prompt: "¿Qué matiz introduce el texto al hablar de consumidores 'más atentos' o 'menos pasivos'?",
      options: [
        "Que esa capacidad se distribuye de manera desigual y depende de recursos previos",
        "Que todos los hogares desarrollan la misma sofisticación económica",
        "Que la adaptación elimina las desigualdades de consumo",
        "Que el aprendizaje vuelve irrelevantes los ingresos disponibles",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto aclara enseguida que esa supuesta sofisticación no se distribuye homogéneamente y depende de tiempo, información y otros recursos.",
      tip: "No tomes una caracterización parcial como si el texto la aplicara a todos por igual.",
      topics: ["inference", "details"],
      isTricky: true,
    },
    {
      id: "per10-q9",
      prompt: "¿Qué estrategias consideradas 'inteligentes' menciona el texto como eficaces pero no siempre accesibles para todos?",
      options: [
        "Comprar por adelantado",
        "Aprovechar descuentos por volumen",
        "Trasladarse hacia comercios más convenientes",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto menciona esas tácticas para mostrar que no todos cuentan con dinero, espacio o tiempo para ponerlas en práctica.",
      tip: "Buscá ejemplos que el texto describa como útiles, pero socialmente desiguales.",
      topics: ["details", "inference"],
    },
    {
      id: "per10-q10",
      prompt: "¿Qué significa en el texto una 'lógica prudencial' del consumo?",
      options: [
        "Consumir más para anticiparse a cualquier crisis",
        "Tomar decisiones con mayor cautela para evitar errores costosos en un contexto incierto",
        "Renunciar por completo a toda forma de deseo o preferencia",
        "Comprar siempre la opción más barata sin evaluar nada más",
      ],
      correctOptionIndex: 1,
      explanation:
        "La prudencia aparece como una forma vigilante de decidir, orientada a reducir riesgos y mantener margen de maniobra.",
      tip: "Definí el concepto por su función en el texto: cautela frente a incertidumbre.",
      topics: ["vocabulary", "conclusion"],
    },
    {
      id: "per10-q11",
      prompt: "¿Qué función cumple el tramo que incorpora la dimensión subjetiva?",
      options: [
        "Mostrar que las decisiones económicas también dependen de percepciones del riesgo, expectativas y confianza",
        "Negar la importancia de precios e ingresos",
        "Sostener que los hogares actúan solo por emociones",
        "Separar por completo la economía de la vida cotidiana",
      ],
      correctOptionIndex: 0,
      explanation:
        "Ese pasaje amplía el análisis más allá de variables objetivas y explica por qué hogares parecidos pueden decidir distinto.",
      tip: "Pensá qué agrega ese tramo al argumento: no reemplaza lo económico, lo complejiza.",
      topics: ["structure", "tools"],
    },
    {
      id: "per10-q12",
      prompt: "Además de variables objetivas, ¿qué factores subjetivos orientan decisiones económicas según el texto?",
      options: [
        "Percepciones sobre el riesgo",
        "Expectativas acerca del futuro",
        "Niveles de confianza en instituciones, empresas o políticas públicas",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto afirma que esos factores ayudan a explicar por qué dos hogares materialmente parecidos pueden actuar de manera distinta.",
      tip: "Si el texto enumera tres dimensiones subjetivas, revisá si la opción integradora las recoge sin alterar su sentido.",
      topics: ["details"],
    },
    {
      id: "per10-q13",
      prompt: "¿Por qué el texto considera insuficiente analizar el consumo solo con indicadores cuantitativos?",
      options: [
        "Porque esos indicadores no muestran estrategias defensivas, cambios temporales y percepciones del riesgo",
        "Porque ya no existen datos sobre gasto en la región",
        "Porque las cifras siempre contradicen la experiencia cotidiana",
        "Porque la economía doméstica dejó de relacionarse con los precios",
        "Porque las estadísticas se ocupan solo de productos de lujo",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto sostiene que saber cuánto cayó o creció el gasto no basta para entender cómo se reorganiza la vida cotidiana bajo presión.",
      tip: "Buscá qué dimensiones del fenómeno quedan fuera cuando solo se mide cantidad.",
      topics: ["conclusion", "inference"],
    },
    {
      id: "per10-q14",
      prompt: "¿Qué quiere decir el texto con que se consolida una 'cultura de precaución'?",
      options: [
        "Que las personas dejan totalmente de consumir",
        "Que muchas decisiones se toman con vigilancia y cuidado para no comprometer el futuro cercano",
        "Que el consumo vuelve a organizarse con rutinas más estables que antes",
        "Que las promociones dejan de tener importancia",
      ],
      correctOptionIndex: 1,
      explanation:
        "La expresión apunta a una manera de consumir más vigilante, donde se posterga, se compara y se evita cometer errores costosos.",
      tip: "No confundas precaución con parálisis total: el texto habla de otra lógica de consumo, no de su desaparición.",
      topics: ["vocabulary", "conclusion"],
      isTricky: true,
    },
    {
      id: "per10-q15",
      prompt: "¿Qué decisiones mínimas menciona el texto como parte de esa vigilancia cotidiana?",
      options: [
        "Cuánto stock conviene tener en casa",
        "Si vale la pena esperar una promoción",
        "Qué producto conviene sustituir",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto muestra que la lógica prudencial no aparece solo en grandes gastos, sino también en pequeñas decisiones repetidas.",
      tip: "Prestá atención al párrafo donde el texto baja la escala desde estrategias amplias a elecciones mínimas.",
      topics: ["details"],
    },
    {
      id: "per10-q16",
      prompt: "¿Cómo cambia la percepción del tiempo según el texto?",
      options: [
        "El mediano plazo gana claridad y estabilidad",
        "El corto plazo gana peso mientras el mediano plazo se vuelve más incierto",
        "La planificación desaparece de forma total",
        "Las decisiones dejan de depender de señales inmediatas",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto dice que la planificación no desaparece, pero se vuelve más cautelosa, reversible y condicionada por el corto plazo.",
      tip: "Buscá el matiz: no es ausencia total de planificación, sino un horizonte temporal más estrecho.",
      topics: ["causeEffect", "details"],
    },
    {
      id: "per10-q17",
      prompt: "¿Qué afirma el texto sobre los hábitos adquiridos en contextos inestables cuando las condiciones mejoran parcialmente?",
      options: [
        "Se abandonan de inmediato",
        "Pueden persistir porque la experiencia de inestabilidad deja marcas duraderas",
        "Se intensifican solo en los sectores de mayores ingresos",
        "Se transforman automáticamente en comportamientos irracionales",
        "Desaparecen si bajan temporalmente algunos precios",
      ],
      correctOptionIndex: 1,
      explanation:
        "El texto subraya que ciertas conductas persisten porque forman parte de una memoria económica y de una disposición aprendida.",
      tip: "Prestá atención a la idea de 'marca' o huella que deja la experiencia prolongada.",
      topics: ["details", "inference"],
    },
    {
      id: "per10-q18",
      prompt: "En escenarios relativamente previsibles, ¿con qué podía vincularse el consumo, según el texto?",
      options: [
        "Bienestar",
        "Elección o recompensa",
        "Pertenencia social",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto enumera esas dimensiones para contrastarlas con la centralidad táctica y defensiva que el consumo adquiere en contextos inestables.",
      tip: "Fijate cómo el texto contrapone el sentido simbólico del consumo en estabilidad e inestabilidad.",
      topics: ["details"],
    },
    {
      id: "per10-q19",
      prompt: "¿Qué se infiere de la expresión 'pedagogía social de la inestabilidad'?",
      options: [
        "Que existen reglas formales únicas que enseñan a consumir",
        "Que los contextos inestables van moldeando conductas compartidas sin necesidad de instrucciones explícitas",
        "Que el mercado deja de tener influencia sobre los hogares",
        "Que aprender a consumir equivale a confiar más en el futuro",
      ],
      correctOptionIndex: 1,
      explanation:
        "La metáfora pedagógica señala que la repetición de contextos volátiles enseña hábitos de cautela, comparación y revisión constante.",
      tip: "Interpretá la metáfora según la idea de aprendizaje colectivo que desarrolla el párrafo.",
      topics: ["inference", "vocabulary"],
    },
    {
      id: "per10-q20",
      prompt: "¿Qué muestra el texto al decir que la economía 'penetra' en conversaciones habituales del hogar?",
      options: [
        "Que deja de ser un tema exclusivo de especialistas y pasa a ordenar decisiones corrientes",
        "Que las familias sustituyen toda conversación por datos financieros",
        "Que la economía solo interesa cuando hay crisis extremas",
        "Que las decisiones de consumo ya no dependen de la experiencia cotidiana",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto sostiene que seguir precios, escuchar recomendaciones y registrar cambios se vuelve parte de la conversación ordinaria.",
      tip: "No exageres la metáfora: el texto habla de mayor presencia cotidiana, no de reemplazo total de otros temas.",
      topics: ["inference", "details"],
      isTricky: true,
    },
    {
      id: "per10-q21",
      prompt: "¿Qué efectos emocionales asocia el texto a la necesidad de permanecer atentos y revisar decisiones constantemente?",
      options: [
        "Cansancio",
        "Irritación",
        "Sensación de fragilidad",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto aclara que la adaptación no es solo práctica: también genera desgaste emocional en la vida cotidiana.",
      tip: "Buscá el párrafo donde el argumento se desplaza del aprendizaje práctico al impacto afectivo.",
      topics: ["details"],
    },
    {
      id: "per10-q22",
      prompt: "¿Qué función cumple el tramo final al reinterpretar conductas que podrían parecer erráticas?",
      options: [
        "Mostrar que muchas decisiones responden a una lógica defensiva consistente cuando se considera la incertidumbre",
        "Probar que los consumidores actúan sin ningún criterio estable",
        "Negar que el riesgo influya en las elecciones cotidianas",
        "Reducir todo el problema a una cuestión de marketing comercial",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto propone que conductas aparentemente contradictorias adquieren sentido si se reconoce cómo la incertidumbre altera horizontes y percepciones.",
      tip: "Pensá qué premisa corrige el autor cuando habla de comportamientos 'a primera vista' erráticos.",
      topics: ["structure", "conclusion"],
    },
    {
      id: "per10-q23",
      prompt: "¿Por qué las políticas orientadas solo a estimular la demanda pueden resultar insuficientes, según el texto?",
      options: [
        "Porque sin un horizonte mínimo de previsibilidad la confianza no se recompone con incentivos aislados",
        "Porque las políticas públicas no influyen nunca sobre el consumo",
        "Porque la demanda dejó de depender de las expectativas futuras",
        "Porque el problema central es únicamente la falta de productos en el mercado",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto sostiene que cuando cualquier cálculo puede quedar rápidamente desactualizado, ofrecer incentivos no alcanza si no se reconstruye confianza.",
      tip: "Buscá qué condición más profunda debe acompañar a los incentivos para que funcionen.",
      topics: ["causeEffect", "inference"],
    },
    {
      id: "per10-q24",
      prompt: "Cuando cualquier cálculo puede quedar desactualizado en poco tiempo, ¿qué se debilita según el texto?",
      options: [
        "La confianza",
        "La posibilidad de sostener rutinas estables",
        "La eficacia de incentivos aislados",
        "Todas las anteriores",
      ],
      correctOptionIndex: 3,
      explanation:
        "El texto enlaza la pérdida de previsibilidad con una confianza más frágil, rutinas menos firmes e incentivos menos efectivos por sí solos.",
      tip: "Si el argumento conecta varios efectos de una misma causa, revisá si la opción totalizadora reproduce esa conexión.",
      topics: ["details", "conclusion"],
    },
    {
      id: "per10-q25",
      prompt: "¿Qué conclusión se extrae cuando el texto dice que el consumo deja de ser un simple indicador de capacidad adquisitiva?",
      options: [
        "Que pasa a expresar también la relación social con el futuro y el grado de confianza en la estabilidad",
        "Que el dinero disponible deja de tener toda importancia",
        "Que el consumo solo refleja decisiones emocionales",
        "Que la incertidumbre afecta solo a bienes durables",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto afirma que la manera de consumir revela no solo cuánto se tiene, sino también cuánta confianza existe en la duración de las condiciones presentes.",
      tip: "La clave está en cómo el texto conecta consumo, tiempo y futuro.",
      topics: ["conclusion", "inference"],
    },
    {
      id: "per10-q26",
      prompt: "¿Qué relación con el tiempo social plantea el texto en su pregunta final?",
      options: [
        "Que el consumo expresa una forma de habitar el tiempo cuando predominan cautela y flexibilidad",
        "Que el tiempo dejó de ser relevante para entender decisiones económicas",
        "Que el futuro se volvió más claro gracias a la volatilidad",
        "Que las personas consumen solo para adaptarse a modas pasajeras",
        "Que la desconfianza no modifica la forma de planificar",
      ],
      correctOptionIndex: 0,
      explanation:
        "El texto cierra vinculando prácticas de consumo con una determinada manera de relacionarse con el futuro y con el tiempo colectivo.",
      tip: "En el cierre, observá cómo el autor transforma una conducta económica en una cuestión temporal más amplia.",
      topics: ["conclusion", "structure"],
    },
    {
      id: "per10-q27",
      prompt: "¿Qué rasgos reúne la síntesis final del texto sobre las transformaciones recientes del consumo latinoamericano?",
      options: [
        "La incertidumbre reorganiza prioridades",
        "Redistribuye capacidades de adaptación de manera desigual",
        "Convierte el consumo en una administración constante del riesgo",
        "A, B y C",
      ],
      correctOptionIndex: 3,
      explanation:
        "La última frase del texto integra justamente esos tres elementos para definir la profundidad del proceso descrito.",
      tip: "Si el cierre enumera varias transformaciones y una opción las reúne sin deformarlas, suele ser la más precisa.",
      topics: ["conclusion", "mainIdea"],
    },
    {
      id: "per10-q28",
      prompt: "En el contexto del texto, ¿qué son los 'márgenes de seguridad' desde los que se toman decisiones?",
      options: [
        "Reservas de recursos, tiempo o estabilidad que permiten decidir con menos vulnerabilidad",
        "Normas legales que impiden cualquier riesgo en el consumo",
        "Límites fijos de precio establecidos por el Estado",
        "Beneficios exclusivos que ofrecen algunas marcas internacionales",
      ],
      correctOptionIndex: 0,
      explanation:
        "La expresión alude a las condiciones materiales o temporales que permiten absorber mejor la incertidumbre y defenderse de la volatilidad.",
      tip: "Interpretá la metáfora según la idea de protección frente al riesgo, no como una norma jurídica.",
      topics: ["vocabulary"],
    },
    {
      id: "per10-q29",
      prompt: "¿Cuál de estas lecturas NO coincide con el texto?",
      options: [
        "La adaptación a la incertidumbre puede desarrollar habilidades, pero también producir desgaste y desigualdades",
        "Las decisiones de consumo en contextos inestables combinan cálculo económico, tiempo y percepciones subjetivas",
        "El texto presenta la adaptación como un proceso uniformemente positivo y distribuido por igual en todos los hogares",
        "La incertidumbre puede dejar huellas duraderas aun cuando el contexto mejore parcialmente",
      ],
      correctOptionIndex: 2,
      explanation:
        "El texto evita una lectura linealmente positiva: reconoce aprendizajes, pero también costos emocionales y desigualdades en la capacidad de adaptación.",
      tip: "Desconfiá de las opciones que simplifican un proceso complejo y ambivalente en una sola valoración.",
      topics: ["inference", "conclusion"],
      isTricky: true,
    },
    {
      id: "per10-q30",
      prompt: "¿Qué resume mejor el sentido global del texto?",
      options: [
        "La inestabilidad económica produce solo restricciones materiales transitorias",
        "El consumo reciente en América Latina debe entenderse como una práctica atravesada por cautela, aprendizaje desigual y administración cotidiana del riesgo",
        "Las decisiones de consumo dependen exclusivamente del nivel de ingreso mensual",
        "La volatilidad económica eliminó cualquier dimensión simbólica del consumo sin dejar huellas duraderas",
      ],
      correctOptionIndex: 1,
      explanation:
        "Esa opción reúne los principales ejes del texto: incertidumbre, reorganización de prioridades, desigualdad en la adaptación y relación con el futuro.",
      tip: "La mejor síntesis debe incluir tanto la dimensión material como la temporal, subjetiva y social del proceso.",
      topics: ["mainIdea", "conclusion"],
    },
  ],
};
